---
fixes:
  - |
    Ensure that the provided rsyslog configuration file is used by the rsyslog
    by restarting the service, it fixes the log offloading feature on
    distributions that start rsyslog before cloud-init.
